[[constraint]]
  branch = "master"
  name = "github.com/golang/protobuf"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.5.1"

[[constraint]]
  name = "github.com/grpc-ecosystem/grpc-gateway"
  version = "1.2.2"

[[constraint]]
  name = "k8s.io/helm"
  version = "2.6.0"
