[[constraint]]
  branch = "master"
  name = "github.com/golang/protobuf"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.5.1"

[[constraint]]
  name = "github.com/grpc-ecosystem/grpc-gateway"
  version = "1.2.2"

[[constraint]]
  name = "k8s.io/helm"
  version = "2.6.0"

[[constraint]]
  name = "k8s.io/client-go"
  version = "4.0.0"

#[[constraint]]
#  name = "k8s.io/apimachinery"
  #branch = "release-1.7"
#  revision = "1fd2e63a9a370677308a42f24fd40c86438afddf"

[[constraint]]
  name = "k8s.io/apimachinery"
  revision = "1fd2e63a9a370677308a42f24fd40c86438afddf"
