#!/bin/bash
set -ex

DIR="$( dirname $( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd ) )"

cd ${DIR}

protoc  \
    --proto_path=${GOPATH}/src \
    --proto_path=./vendor/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis \
    --proto_path=./vendor/k8s.io/helm/_proto \
    --proto_path=./proto \
    --go_out=plugins=grpc,Mhapi/release/release.proto=k8s.io/helm/pkg/proto/hapi/release:./api \
    --govalidators_out=Mhapi/release/release.proto=k8s.io/helm/pkg/proto/hapi/release:./api \
    ./proto/*.proto

protoc \
    --proto_path=$GOPATH/src \
    --proto_path=$GOPATH/src/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis \
    --proto_path=./vendor/k8s.io/helm/_proto \
    --proto_path=./proto \
    --grpc-gateway_out=logtostderr=true:./api \
    ./proto/*.proto

