#!/bin/bash
set -ex

protoc  \
    --proto_path=${GOPATH}/src \
    --proto_path=$GOPATH/src/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis \
    --proto_path=./proto \
    --go_out=plugins=grpc:./api \
    --govalidators_out=./api \
    ./proto/*.proto

protoc \
    --proto_path=$GOPATH/src \
    --proto_path=$GOPATH/src/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis \
    --proto_path=./proto \
    --grpc-gateway_out=logtostderr=true:./api \
    ./proto/*.proto
