// Code generated by protoc-gen-gogo.
// source: application.proto
// DO NOT EDIT!

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	application.proto
	artifact.proto
	cluster.proto
	deployment.proto
	service.proto

It has these top-level messages:
	Application
	Target
	GetApplicationRequest
	ListApplicationsRequest
	ApplicationList
	CreateApplicationRequest
	Artifact
	ArtifactList
	GetArtifactRequest
	ListArtifactsRequest
	CreateArtifactRequest
	Cluster
	Deployment
	Resource
	DeploymentList
	GetDeploymentRequest
	ListDeploymentsRequest
	CreateDeploymentRequest
*/
package api

import fmt "fmt"
import github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
import proto "github.com/golang/protobuf/proto"
import math "math"
import _ "github.com/mwitkow/go-proto-validators"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *Application) Validate() error {
	// Validation of proto3 map<> fields is unsupported.
	for _, item := range this.Targets {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Targets", err)
			}
		}
	}
	return nil
}
func (this *Target) Validate() error {
	// Validation of proto3 map<> fields is unsupported.
	return nil
}
func (this *GetApplicationRequest) Validate() error {
	return nil
}
func (this *ListApplicationsRequest) Validate() error {
	return nil
}
func (this *ApplicationList) Validate() error {
	for _, item := range this.Items {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Items", err)
			}
		}
	}
	return nil
}
func (this *CreateApplicationRequest) Validate() error {
	if nil == this.Application {
		return github_com_mwitkow_go_proto_validators.FieldError("Application", fmt.Errorf("message must exist"))
	}
	if this.Application != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Application); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Application", err)
		}
	}
	return nil
}
