// Code generated by protoc-gen-go. DO NOT EDIT.
// source: application.proto

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	application.proto
	artifact.proto
	cluster.proto
	config.proto
	deployment.proto
	service.proto

It has these top-level messages:
	Application
	Target
	GetApplicationRequest
	ListApplicationRequest
	ApplicationList
	Artifact
	ArtifactBuild
	ArtifactList
	ArtifactBuildList
	GetArtifactRequest
	ListArtifactsRequest
	GetArtifactBuildRequest
	ListArtifactBuildsRequest
	CreateArtifactRequest
	Cluster
	Config
	Value
	Deployment
	Resource
	DeploymentList
	GetDeploymentRequest
	ListDeploymentsRequest
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Application struct {
	Name     string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Chart    string `protobuf:"bytes,2,opt,name=chart" json:"chart,omitempty"`
	Artifact string `protobuf:"bytes,3,opt,name=artifact" json:"artifact,omitempty"`
	// Default config for this target.
	Defaults *Config   `protobuf:"bytes,4,opt,name=defaults" json:"defaults,omitempty"`
	Targets  []*Target `protobuf:"bytes,5,rep,name=targets" json:"targets,omitempty"`
}

func (m *Application) Reset()                    { *m = Application{} }
func (m *Application) String() string            { return proto.CompactTextString(m) }
func (*Application) ProtoMessage()               {}
func (*Application) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Application) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Application) GetChart() string {
	if m != nil {
		return m.Chart
	}
	return ""
}

func (m *Application) GetArtifact() string {
	if m != nil {
		return m.Artifact
	}
	return ""
}

func (m *Application) GetDefaults() *Config {
	if m != nil {
		return m.Defaults
	}
	return nil
}

func (m *Application) GetTargets() []*Target {
	if m != nil {
		return m.Targets
	}
	return nil
}

type Target struct {
	Name      string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Cluster   string `protobuf:"bytes,2,opt,name=cluster" json:"cluster,omitempty"`
	Namespace string `protobuf:"bytes,3,opt,name=namespace" json:"namespace,omitempty"`
	// Config for this target.
	Values *Config `protobuf:"bytes,4,opt,name=values" json:"values,omitempty"`
}

func (m *Target) Reset()                    { *m = Target{} }
func (m *Target) String() string            { return proto.CompactTextString(m) }
func (*Target) ProtoMessage()               {}
func (*Target) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Target) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Target) GetCluster() string {
	if m != nil {
		return m.Cluster
	}
	return ""
}

func (m *Target) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *Target) GetValues() *Config {
	if m != nil {
		return m.Values
	}
	return nil
}

type GetApplicationRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *GetApplicationRequest) Reset()                    { *m = GetApplicationRequest{} }
func (m *GetApplicationRequest) String() string            { return proto.CompactTextString(m) }
func (*GetApplicationRequest) ProtoMessage()               {}
func (*GetApplicationRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetApplicationRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ListApplicationRequest struct {
}

func (m *ListApplicationRequest) Reset()                    { *m = ListApplicationRequest{} }
func (m *ListApplicationRequest) String() string            { return proto.CompactTextString(m) }
func (*ListApplicationRequest) ProtoMessage()               {}
func (*ListApplicationRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type ApplicationList struct {
	Items []*Application `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
}

func (m *ApplicationList) Reset()                    { *m = ApplicationList{} }
func (m *ApplicationList) String() string            { return proto.CompactTextString(m) }
func (*ApplicationList) ProtoMessage()               {}
func (*ApplicationList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ApplicationList) GetItems() []*Application {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
	proto.RegisterType((*Application)(nil), "darrell.api.Application")
	proto.RegisterType((*Target)(nil), "darrell.api.Target")
	proto.RegisterType((*GetApplicationRequest)(nil), "darrell.api.GetApplicationRequest")
	proto.RegisterType((*ListApplicationRequest)(nil), "darrell.api.ListApplicationRequest")
	proto.RegisterType((*ApplicationList)(nil), "darrell.api.ApplicationList")
}

func init() { proto.RegisterFile("application.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 283 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0xbd, 0x4e, 0xf3, 0x30,
	0x14, 0x86, 0xe5, 0xaf, 0x4d, 0xda, 0x9e, 0x7c, 0x12, 0xc2, 0xfc, 0xc8, 0xaa, 0x18, 0xa2, 0x4c,
	0x95, 0x2a, 0x82, 0x04, 0x57, 0x50, 0x18, 0x58, 0x98, 0x22, 0x26, 0xb6, 0x83, 0xeb, 0x14, 0x4b,
	0x6e, 0x62, 0xec, 0x13, 0x76, 0xae, 0x89, 0x1b, 0x44, 0x75, 0xd2, 0x36, 0x88, 0x88, 0xcd, 0xe7,
	0x7d, 0x1f, 0x5b, 0x8f, 0x8e, 0xe1, 0x14, 0xad, 0x35, 0x5a, 0x22, 0xe9, 0xba, 0xca, 0xad, 0xab,
	0xa9, 0xe6, 0xc9, 0x1a, 0x9d, 0x53, 0xc6, 0xe4, 0x68, 0xf5, 0xfc, 0xbf, 0xac, 0xab, 0x52, 0x6f,
	0xda, 0x2a, 0xfb, 0x62, 0x90, 0xac, 0x8e, 0x17, 0x38, 0x87, 0x71, 0x85, 0x5b, 0x25, 0x58, 0xca,
	0x16, 0xb3, 0x22, 0x9c, 0xf9, 0x39, 0x44, 0xf2, 0x0d, 0x1d, 0x89, 0x7f, 0x21, 0x6c, 0x07, 0x3e,
	0x87, 0x29, 0x3a, 0xd2, 0x25, 0x4a, 0x12, 0xa3, 0x50, 0x1c, 0x66, 0x7e, 0x03, 0xd3, 0xb5, 0x2a,
	0xb1, 0x31, 0xe4, 0xc5, 0x38, 0x65, 0x8b, 0xe4, 0xf6, 0x2c, 0xef, 0x39, 0xe4, 0x0f, 0x41, 0xa1,
	0x38, 0x40, 0xfc, 0x1a, 0x26, 0x84, 0x6e, 0xa3, 0xc8, 0x8b, 0x28, 0x1d, 0xfd, 0xe2, 0x9f, 0x43,
	0x57, 0xec, 0x99, 0xec, 0x93, 0x41, 0xdc, 0x66, 0x83, 0xc2, 0x02, 0x26, 0xd2, 0x34, 0x9e, 0x94,
	0xeb, 0x94, 0xf7, 0x23, 0xbf, 0x82, 0xd9, 0x8e, 0xf0, 0x16, 0xa5, 0xea, 0xac, 0x8f, 0x01, 0x5f,
	0x42, 0xfc, 0x81, 0xa6, 0x51, 0x7f, 0x4a, 0x77, 0x48, 0xb6, 0x84, 0x8b, 0x47, 0x45, 0xbd, 0xdd,
	0x15, 0xea, 0xbd, 0x51, 0x7e, 0xd0, 0x28, 0x13, 0x70, 0xf9, 0xa4, 0xfd, 0x00, 0x9d, 0xad, 0xe0,
	0xa4, 0x97, 0xee, 0x20, 0x9e, 0x43, 0xa4, 0x49, 0x6d, 0xbd, 0x60, 0x61, 0x15, 0xe2, 0x87, 0x45,
	0xff, 0x89, 0x16, 0xbb, 0x8f, 0x5e, 0x46, 0x68, 0xf5, 0x6b, 0x1c, 0x7e, 0xf4, 0xee, 0x3b, 0x00,
	0x00, 0xff, 0xff, 0x26, 0xee, 0x68, 0xf6, 0x01, 0x02, 0x00, 0x00,
}
