// Code generated by protoc-gen-gogo.
// source: application.proto
// DO NOT EDIT!

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	application.proto
	artifact.proto
	cluster.proto
	config.proto
	deployment.proto
	service.proto

It has these top-level messages:
	Application
	Target
	GetApplicationRequest
	ListApplicationRequest
	ApplicationList
	Artifact
	ArtifactBuild
	ArtifactList
	ArtifactBuildList
	GetArtifactRequest
	ListArtifactsRequest
	GetArtifactBuildRequest
	ListArtifactBuildsRequest
	CreateArtifactRequest
	Cluster
	Config
	Value
	Deployment
	Resource
	DeploymentList
	GetDeploymentRequest
	ListDeploymentsRequest
*/
package api

import github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *Application) Validate() error {
	if this.Defaults != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Defaults); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Defaults", err)
		}
	}
	for _, item := range this.Targets {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Targets", err)
			}
		}
	}
	return nil
}
func (this *Target) Validate() error {
	if this.Values != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Values); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Values", err)
		}
	}
	return nil
}
func (this *GetApplicationRequest) Validate() error {
	return nil
}
func (this *ListApplicationRequest) Validate() error {
	return nil
}
func (this *ApplicationList) Validate() error {
	for _, item := range this.Items {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Items", err)
			}
		}
	}
	return nil
}
