// Code generated by protoc-gen-go. DO NOT EDIT.
// source: application.proto

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	application.proto
	artifact.proto
	cluster.proto
	deployment.proto
	service.proto

It has these top-level messages:
	Application
	Target
	GetApplicationRequest
	ListApplicationsRequest
	ApplicationList
	CreateApplicationRequest
	Artifact
	ArtifactList
	GetArtifactRequest
	ListArtifactsRequest
	CreateArtifactRequest
	Cluster
	Deployment
	Resource
	DeploymentList
	GetDeploymentRequest
	ListDeploymentsRequest
	CreateDeploymentRequest
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/mwitkow/go-proto-validators"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Application struct {
	Name     string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Chart    string `protobuf:"bytes,2,opt,name=chart" json:"chart,omitempty"`
	Artifact string `protobuf:"bytes,3,opt,name=artifact" json:"artifact,omitempty"`
	// Default config for this target.
	Defaults map[string]string `protobuf:"bytes,4,rep,name=defaults" json:"defaults,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// deployment target
	Targets []*Target `protobuf:"bytes,5,rep,name=targets" json:"targets,omitempty"`
}

func (m *Application) Reset()                    { *m = Application{} }
func (m *Application) String() string            { return proto.CompactTextString(m) }
func (*Application) ProtoMessage()               {}
func (*Application) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Application) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Application) GetChart() string {
	if m != nil {
		return m.Chart
	}
	return ""
}

func (m *Application) GetArtifact() string {
	if m != nil {
		return m.Artifact
	}
	return ""
}

func (m *Application) GetDefaults() map[string]string {
	if m != nil {
		return m.Defaults
	}
	return nil
}

func (m *Application) GetTargets() []*Target {
	if m != nil {
		return m.Targets
	}
	return nil
}

type Target struct {
	Name      string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Cluster   string `protobuf:"bytes,2,opt,name=cluster" json:"cluster,omitempty"`
	Namespace string `protobuf:"bytes,3,opt,name=namespace" json:"namespace,omitempty"`
	// values for this target.
	Values map[string]string `protobuf:"bytes,4,rep,name=values" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Target) Reset()                    { *m = Target{} }
func (m *Target) String() string            { return proto.CompactTextString(m) }
func (*Target) ProtoMessage()               {}
func (*Target) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Target) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Target) GetCluster() string {
	if m != nil {
		return m.Cluster
	}
	return ""
}

func (m *Target) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *Target) GetValues() map[string]string {
	if m != nil {
		return m.Values
	}
	return nil
}

type GetApplicationRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *GetApplicationRequest) Reset()                    { *m = GetApplicationRequest{} }
func (m *GetApplicationRequest) String() string            { return proto.CompactTextString(m) }
func (*GetApplicationRequest) ProtoMessage()               {}
func (*GetApplicationRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetApplicationRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ListApplicationsRequest struct {
}

func (m *ListApplicationsRequest) Reset()                    { *m = ListApplicationsRequest{} }
func (m *ListApplicationsRequest) String() string            { return proto.CompactTextString(m) }
func (*ListApplicationsRequest) ProtoMessage()               {}
func (*ListApplicationsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type ApplicationList struct {
	Items []*Application `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
}

func (m *ApplicationList) Reset()                    { *m = ApplicationList{} }
func (m *ApplicationList) String() string            { return proto.CompactTextString(m) }
func (*ApplicationList) ProtoMessage()               {}
func (*ApplicationList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ApplicationList) GetItems() []*Application {
	if m != nil {
		return m.Items
	}
	return nil
}

type CreateApplicationRequest struct {
	Application *Application `protobuf:"bytes,1,opt,name=application" json:"application,omitempty"`
	Overwrite   bool         `protobuf:"varint,2,opt,name=overwrite" json:"overwrite,omitempty"`
}

func (m *CreateApplicationRequest) Reset()                    { *m = CreateApplicationRequest{} }
func (m *CreateApplicationRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateApplicationRequest) ProtoMessage()               {}
func (*CreateApplicationRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *CreateApplicationRequest) GetApplication() *Application {
	if m != nil {
		return m.Application
	}
	return nil
}

func (m *CreateApplicationRequest) GetOverwrite() bool {
	if m != nil {
		return m.Overwrite
	}
	return false
}

func init() {
	proto.RegisterType((*Application)(nil), "alecton.api.Application")
	proto.RegisterType((*Target)(nil), "alecton.api.Target")
	proto.RegisterType((*GetApplicationRequest)(nil), "alecton.api.GetApplicationRequest")
	proto.RegisterType((*ListApplicationsRequest)(nil), "alecton.api.ListApplicationsRequest")
	proto.RegisterType((*ApplicationList)(nil), "alecton.api.ApplicationList")
	proto.RegisterType((*CreateApplicationRequest)(nil), "alecton.api.CreateApplicationRequest")
}

func init() { proto.RegisterFile("application.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 424 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xdf, 0x8a, 0x13, 0x31,
	0x14, 0xc6, 0x99, 0x76, 0xa7, 0xdb, 0x3d, 0x83, 0xa8, 0x51, 0x31, 0x96, 0x85, 0x2d, 0x73, 0x21,
	0x0b, 0xd2, 0x14, 0x14, 0xfc, 0x7b, 0xb5, 0x55, 0xf1, 0xc6, 0xab, 0x20, 0x5e, 0x78, 0x77, 0x76,
	0x9a, 0xed, 0x86, 0x9d, 0x36, 0x63, 0x72, 0xa6, 0xa5, 0xe0, 0x9b, 0xf8, 0x42, 0xbe, 0x85, 0xe0,
	0x93, 0x48, 0x93, 0x69, 0x9b, 0x81, 0x2a, 0xec, 0x5d, 0xf2, 0xe5, 0x97, 0x6f, 0xf2, 0x7d, 0x73,
	0xe0, 0x3e, 0x56, 0x55, 0xa9, 0x0b, 0x24, 0x6d, 0x16, 0xa2, 0xb2, 0x86, 0x0c, 0xcb, 0xa6, 0x68,
	0xad, 0x2a, 0x4b, 0x81, 0x95, 0x1e, 0xbc, 0x9c, 0x69, 0xba, 0xae, 0x2f, 0x45, 0x61, 0xe6, 0xe3,
	0xf9, 0x4a, 0xd3, 0x8d, 0x59, 0x8d, 0x67, 0x66, 0xe4, 0xc9, 0xd1, 0x12, 0x4b, 0x3d, 0x45, 0x32,
	0xd6, 0x8d, 0x77, 0xcb, 0x60, 0x92, 0xff, 0xec, 0x40, 0x76, 0xb1, 0xb7, 0x66, 0x03, 0x38, 0x5a,
	0xe0, 0x5c, 0xf1, 0x64, 0x98, 0x9c, 0x9f, 0x4c, 0x7a, 0x7f, 0x7e, 0x9f, 0x75, 0x86, 0x89, 0xf4,
	0x1a, 0x3b, 0x85, 0xb4, 0xb8, 0x46, 0x4b, 0xbc, 0xd3, 0x3a, 0x0c, 0x22, 0xcb, 0xa1, 0x8f, 0x96,
	0xf4, 0x15, 0x16, 0xc4, 0xbb, 0x2d, 0x60, 0xa7, 0xb3, 0x09, 0xf4, 0xa7, 0xea, 0x0a, 0xeb, 0x92,
	0x1c, 0x3f, 0x1a, 0x76, 0xcf, 0xb3, 0xe7, 0x4f, 0x45, 0x94, 0x42, 0x44, 0x2f, 0x11, 0x1f, 0x1a,
	0xf0, 0xe3, 0x82, 0xec, 0x5a, 0xee, 0xee, 0xb1, 0x11, 0x1c, 0x13, 0xda, 0x99, 0x22, 0xc7, 0x53,
	0x6f, 0xf1, 0xa0, 0x65, 0xf1, 0xc5, 0x9f, 0xc9, 0x2d, 0x33, 0x78, 0x07, 0x77, 0x5a, 0x4e, 0xec,
	0x1e, 0x74, 0x6f, 0xd4, 0x3a, 0x04, 0x94, 0x9b, 0x25, 0x7b, 0x08, 0xe9, 0x12, 0xcb, 0x5a, 0x85,
	0x5c, 0x32, 0x6c, 0xde, 0x76, 0x5e, 0x27, 0xf9, 0xaf, 0x04, 0x7a, 0xc1, 0x90, 0xb1, 0xb8, 0x98,
	0xa6, 0x10, 0x0e, 0xc7, 0x45, 0x59, 0x3b, 0x52, 0xb6, 0xb9, 0xba, 0xdd, 0xb2, 0x53, 0x38, 0xd9,
	0x10, 0xae, 0xc2, 0x42, 0x85, 0x36, 0xe4, 0x5e, 0x60, 0xaf, 0xa0, 0xe7, 0xbf, 0xb1, 0x2d, 0xe1,
	0xec, 0x40, 0x02, 0xf1, 0xd5, 0x13, 0x21, 0x7d, 0x83, 0x0f, 0xde, 0x40, 0x16, 0xc9, 0xb7, 0x8a,
	0xf2, 0x0c, 0x1e, 0x7d, 0x52, 0x14, 0x15, 0x2c, 0xd5, 0xf7, 0x5a, 0xb9, 0x83, 0xc1, 0xf2, 0x27,
	0xf0, 0xf8, 0xb3, 0x76, 0x31, 0xed, 0x1a, 0x3c, 0xbf, 0x80, 0xbb, 0x91, 0xbc, 0xa1, 0x98, 0x80,
	0x54, 0x93, 0x9a, 0x3b, 0x9e, 0xf8, 0x34, 0xfc, 0x5f, 0xbf, 0x54, 0x06, 0x2c, 0xff, 0x01, 0xfc,
	0xbd, 0x55, 0x48, 0xea, 0xc0, 0x6b, 0x26, 0x90, 0x45, 0x93, 0xee, 0x1f, 0xf5, 0x1f, 0xc7, 0xdd,
	0x88, 0xc5, 0x97, 0x36, 0xe5, 0x9b, 0xa5, 0xb2, 0x2b, 0xab, 0x29, 0x14, 0xd1, 0x97, 0x7b, 0x61,
	0x92, 0x7e, 0xeb, 0x62, 0xa5, 0x2f, 0x7b, 0x7e, 0xfe, 0x5f, 0xfc, 0x0d, 0x00, 0x00, 0xff, 0xff,
	0x01, 0xe1, 0x42, 0x71, 0x59, 0x03, 0x00, 0x00,
}
