// Code generated by protoc-gen-go. DO NOT EDIT.
// source: artifact.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/mwitkow/go-proto-validators"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Artifact struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *Artifact) Reset()                    { *m = Artifact{} }
func (m *Artifact) String() string            { return proto.CompactTextString(m) }
func (*Artifact) ProtoMessage()               {}
func (*Artifact) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *Artifact) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ArtifactBuild struct {
	Artifact string `protobuf:"bytes,1,opt,name=artifact" json:"artifact,omitempty"`
	Version  string `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
	Branch   string `protobuf:"bytes,3,opt,name=branch" json:"branch,omitempty"`
	Image    string `protobuf:"bytes,4,opt,name=image" json:"image,omitempty"`
}

func (m *ArtifactBuild) Reset()                    { *m = ArtifactBuild{} }
func (m *ArtifactBuild) String() string            { return proto.CompactTextString(m) }
func (*ArtifactBuild) ProtoMessage()               {}
func (*ArtifactBuild) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *ArtifactBuild) GetArtifact() string {
	if m != nil {
		return m.Artifact
	}
	return ""
}

func (m *ArtifactBuild) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *ArtifactBuild) GetBranch() string {
	if m != nil {
		return m.Branch
	}
	return ""
}

func (m *ArtifactBuild) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

type ArtifactList struct {
	Items []*Artifact `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
}

func (m *ArtifactList) Reset()                    { *m = ArtifactList{} }
func (m *ArtifactList) String() string            { return proto.CompactTextString(m) }
func (*ArtifactList) ProtoMessage()               {}
func (*ArtifactList) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *ArtifactList) GetItems() []*Artifact {
	if m != nil {
		return m.Items
	}
	return nil
}

type ArtifactBuildList struct {
	Items []*ArtifactBuild `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
}

func (m *ArtifactBuildList) Reset()                    { *m = ArtifactBuildList{} }
func (m *ArtifactBuildList) String() string            { return proto.CompactTextString(m) }
func (*ArtifactBuildList) ProtoMessage()               {}
func (*ArtifactBuildList) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *ArtifactBuildList) GetItems() []*ArtifactBuild {
	if m != nil {
		return m.Items
	}
	return nil
}

type GetArtifactRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *GetArtifactRequest) Reset()                    { *m = GetArtifactRequest{} }
func (m *GetArtifactRequest) String() string            { return proto.CompactTextString(m) }
func (*GetArtifactRequest) ProtoMessage()               {}
func (*GetArtifactRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *GetArtifactRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ListArtifactsRequest struct {
}

func (m *ListArtifactsRequest) Reset()                    { *m = ListArtifactsRequest{} }
func (m *ListArtifactsRequest) String() string            { return proto.CompactTextString(m) }
func (*ListArtifactsRequest) ProtoMessage()               {}
func (*ListArtifactsRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

type GetArtifactBuildRequest struct {
	Name     string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Artifact string `protobuf:"bytes,2,opt,name=artifact" json:"artifact,omitempty"`
}

func (m *GetArtifactBuildRequest) Reset()                    { *m = GetArtifactBuildRequest{} }
func (m *GetArtifactBuildRequest) String() string            { return proto.CompactTextString(m) }
func (*GetArtifactBuildRequest) ProtoMessage()               {}
func (*GetArtifactBuildRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func (m *GetArtifactBuildRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetArtifactBuildRequest) GetArtifact() string {
	if m != nil {
		return m.Artifact
	}
	return ""
}

type ListArtifactBuildsRequest struct {
	// is name is set, get for a particular artifact
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *ListArtifactBuildsRequest) Reset()                    { *m = ListArtifactBuildsRequest{} }
func (m *ListArtifactBuildsRequest) String() string            { return proto.CompactTextString(m) }
func (*ListArtifactBuildsRequest) ProtoMessage()               {}
func (*ListArtifactBuildsRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

func (m *ListArtifactBuildsRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateArtifactRequest struct {
	Artifact  *Artifact `protobuf:"bytes,1,opt,name=artifact" json:"artifact,omitempty"`
	Overwrite bool      `protobuf:"varint,2,opt,name=overwrite" json:"overwrite,omitempty"`
}

func (m *CreateArtifactRequest) Reset()                    { *m = CreateArtifactRequest{} }
func (m *CreateArtifactRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateArtifactRequest) ProtoMessage()               {}
func (*CreateArtifactRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8} }

func (m *CreateArtifactRequest) GetArtifact() *Artifact {
	if m != nil {
		return m.Artifact
	}
	return nil
}

func (m *CreateArtifactRequest) GetOverwrite() bool {
	if m != nil {
		return m.Overwrite
	}
	return false
}

func init() {
	proto.RegisterType((*Artifact)(nil), "darrell.api.Artifact")
	proto.RegisterType((*ArtifactBuild)(nil), "darrell.api.ArtifactBuild")
	proto.RegisterType((*ArtifactList)(nil), "darrell.api.ArtifactList")
	proto.RegisterType((*ArtifactBuildList)(nil), "darrell.api.ArtifactBuildList")
	proto.RegisterType((*GetArtifactRequest)(nil), "darrell.api.GetArtifactRequest")
	proto.RegisterType((*ListArtifactsRequest)(nil), "darrell.api.ListArtifactsRequest")
	proto.RegisterType((*GetArtifactBuildRequest)(nil), "darrell.api.GetArtifactBuildRequest")
	proto.RegisterType((*ListArtifactBuildsRequest)(nil), "darrell.api.ListArtifactBuildsRequest")
	proto.RegisterType((*CreateArtifactRequest)(nil), "darrell.api.CreateArtifactRequest")
}

func init() { proto.RegisterFile("artifact.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 348 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x5f, 0x4b, 0xf3, 0x30,
	0x14, 0xc6, 0xe9, 0xfe, 0xbd, 0xdb, 0xd9, 0xab, 0x60, 0xd8, 0x66, 0x2d, 0x82, 0x23, 0x17, 0x32,
	0x90, 0xb5, 0xa2, 0x20, 0x88, 0x57, 0x4e, 0x44, 0x04, 0xaf, 0x7a, 0xe9, 0x5d, 0xb6, 0xc5, 0x2d,
	0xd8, 0x2e, 0x35, 0x39, 0x5b, 0x3f, 0xae, 0xe0, 0x27, 0x11, 0xd3, 0xa6, 0x6b, 0x87, 0xf3, 0xae,
	0xe7, 0xe4, 0xe9, 0xef, 0x3c, 0x79, 0x72, 0xe0, 0x90, 0x29, 0x14, 0x6f, 0x6c, 0x86, 0x7e, 0xa2,
	0x24, 0x4a, 0xd2, 0x9d, 0x33, 0xa5, 0x78, 0x14, 0xf9, 0x2c, 0x11, 0xde, 0xcd, 0x42, 0xe0, 0x72,
	0x3d, 0xf5, 0x67, 0x32, 0x0e, 0xe2, 0x54, 0xe0, 0xbb, 0x4c, 0x83, 0x85, 0x1c, 0x1b, 0xe5, 0x78,
	0xc3, 0x22, 0x31, 0x67, 0x28, 0x95, 0x0e, 0x8a, 0xcf, 0x0c, 0x42, 0xcf, 0xa1, 0x7d, 0x9f, 0x63,
	0x89, 0x07, 0x8d, 0x15, 0x8b, 0xb9, 0xeb, 0x0c, 0x9d, 0x51, 0x67, 0xd2, 0xfa, 0xfa, 0x3c, 0xab,
	0x0d, 0x9d, 0xd0, 0xf4, 0xa8, 0x86, 0x03, 0xab, 0x9b, 0xac, 0x45, 0x34, 0x27, 0x1e, 0xb4, 0xad,
	0x9f, 0xec, 0x87, 0xb0, 0xa8, 0x89, 0x0b, 0xff, 0x36, 0x5c, 0x69, 0x21, 0x57, 0x6e, 0xcd, 0x1c,
	0xd9, 0x92, 0x0c, 0xa0, 0x35, 0x55, 0x6c, 0x35, 0x5b, 0xba, 0x75, 0x73, 0x90, 0x57, 0xa4, 0x07,
	0x4d, 0x11, 0xb3, 0x05, 0x77, 0x1b, 0xa6, 0x9d, 0x15, 0xf4, 0x0e, 0xfe, 0xdb, 0xa1, 0x2f, 0x42,
	0x23, 0xb9, 0x80, 0xa6, 0x40, 0x1e, 0x6b, 0xd7, 0x19, 0xd6, 0x47, 0xdd, 0xab, 0xbe, 0x5f, 0x4a,
	0xc0, 0xb7, 0xca, 0x30, 0xd3, 0xd0, 0x47, 0x38, 0xaa, 0x38, 0x36, 0x84, 0xcb, 0x2a, 0xc1, 0xfb,
	0x95, 0x60, 0xe4, 0x16, 0x33, 0x02, 0xf2, 0xc4, 0xb1, 0x80, 0xf3, 0x8f, 0x35, 0xd7, 0x48, 0x48,
	0x39, 0xaa, 0x3c, 0xa2, 0x01, 0xf4, 0x7e, 0x66, 0x58, 0xa9, 0xce, 0xb5, 0xf4, 0x19, 0x8e, 0x4b,
	0x84, 0x0c, 0xbe, 0x1f, 0x53, 0x09, 0xb6, 0x56, 0x0d, 0x96, 0x06, 0x70, 0x52, 0x1e, 0x61, 0x58,
	0xfa, 0x2f, 0x4f, 0x09, 0xf4, 0x1f, 0x14, 0x67, 0xc8, 0x77, 0x2f, 0x70, 0xbb, 0xf3, 0x7c, 0xfb,
	0xd2, 0x2c, 0xd6, 0x60, 0xfb, 0xba, 0xa7, 0xd0, 0x91, 0x1b, 0xae, 0x52, 0x25, 0x90, 0x1b, 0x87,
	0xed, 0x70, 0xdb, 0x98, 0x34, 0x5f, 0xeb, 0x2c, 0x11, 0xd3, 0x96, 0x59, 0xaf, 0xeb, 0xef, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x8c, 0xed, 0x33, 0x08, 0xb5, 0x02, 0x00, 0x00,
}
