// Code generated by protoc-gen-gogo.
// source: artifact.proto
// DO NOT EDIT!

package api

import fmt "fmt"
import github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
import proto "github.com/golang/protobuf/proto"
import math "math"
import _ "github.com/mwitkow/go-proto-validators"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *Artifact) Validate() error {
	return nil
}
func (this *ArtifactBuild) Validate() error {
	return nil
}
func (this *ArtifactList) Validate() error {
	for _, item := range this.Items {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Items", err)
			}
		}
	}
	return nil
}
func (this *ArtifactBuildList) Validate() error {
	for _, item := range this.Items {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Items", err)
			}
		}
	}
	return nil
}
func (this *GetArtifactRequest) Validate() error {
	return nil
}
func (this *ListArtifactsRequest) Validate() error {
	return nil
}
func (this *GetArtifactBuildRequest) Validate() error {
	return nil
}
func (this *ListArtifactBuildsRequest) Validate() error {
	return nil
}
func (this *CreateArtifactRequest) Validate() error {
	if nil == this.Artifact {
		return github_com_mwitkow_go_proto_validators.FieldError("Artifact", fmt.Errorf("message must exist"))
	}
	if this.Artifact != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Artifact); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Artifact", err)
		}
	}
	return nil
}
