// Code generated by protoc-gen-gogo.
// source: config.proto
// DO NOT EDIT!

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *Config) Validate() error {
	// Validation of proto3 map<> fields is unsupported.
	return nil
}
func (this *Value) Validate() error {
	return nil
}
