// Code generated by protoc-gen-go. DO NOT EDIT.
// source: deployment.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Deployment struct {
	Id          string      `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Application string      `protobuf:"bytes,2,opt,name=application" json:"application,omitempty"`
	Target      string      `protobuf:"bytes,3,opt,name=target" json:"target,omitempty"`
	Artifact    string      `protobuf:"bytes,4,opt,name=artifact" json:"artifact,omitempty"`
	Version     string      `protobuf:"bytes,5,opt,name=version" json:"version,omitempty"`
	Active      bool        `protobuf:"varint,6,opt,name=active" json:"active,omitempty"`
	Resources   []*Resource `protobuf:"bytes,7,rep,name=resources" json:"resources,omitempty"`
}

func (m *Deployment) Reset()                    { *m = Deployment{} }
func (m *Deployment) String() string            { return proto.CompactTextString(m) }
func (*Deployment) ProtoMessage()               {}
func (*Deployment) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{0} }

func (m *Deployment) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Deployment) GetApplication() string {
	if m != nil {
		return m.Application
	}
	return ""
}

func (m *Deployment) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *Deployment) GetArtifact() string {
	if m != nil {
		return m.Artifact
	}
	return ""
}

func (m *Deployment) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Deployment) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *Deployment) GetResources() []*Resource {
	if m != nil {
		return m.Resources
	}
	return nil
}

type Resource struct {
	Name      string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Cluster   string `protobuf:"bytes,2,opt,name=cluster" json:"cluster,omitempty"`
	Namespace string `protobuf:"bytes,3,opt,name=namespace" json:"namespace,omitempty"`
	Data      string `protobuf:"bytes,4,opt,name=data" json:"data,omitempty"`
}

func (m *Resource) Reset()                    { *m = Resource{} }
func (m *Resource) String() string            { return proto.CompactTextString(m) }
func (*Resource) ProtoMessage()               {}
func (*Resource) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{1} }

func (m *Resource) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Resource) GetCluster() string {
	if m != nil {
		return m.Cluster
	}
	return ""
}

func (m *Resource) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *Resource) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type DeploymentList struct {
	Items []*Deployment `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
}

func (m *DeploymentList) Reset()                    { *m = DeploymentList{} }
func (m *DeploymentList) String() string            { return proto.CompactTextString(m) }
func (*DeploymentList) ProtoMessage()               {}
func (*DeploymentList) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{2} }

func (m *DeploymentList) GetItems() []*Deployment {
	if m != nil {
		return m.Items
	}
	return nil
}

type GetDeploymentRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetDeploymentRequest) Reset()                    { *m = GetDeploymentRequest{} }
func (m *GetDeploymentRequest) String() string            { return proto.CompactTextString(m) }
func (*GetDeploymentRequest) ProtoMessage()               {}
func (*GetDeploymentRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{3} }

func (m *GetDeploymentRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ListDeploymentsRequest struct {
	Application string `protobuf:"bytes,1,opt,name=application" json:"application,omitempty"`
}

func (m *ListDeploymentsRequest) Reset()                    { *m = ListDeploymentsRequest{} }
func (m *ListDeploymentsRequest) String() string            { return proto.CompactTextString(m) }
func (*ListDeploymentsRequest) ProtoMessage()               {}
func (*ListDeploymentsRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{4} }

func (m *ListDeploymentsRequest) GetApplication() string {
	if m != nil {
		return m.Application
	}
	return ""
}

func init() {
	proto.RegisterType((*Deployment)(nil), "darrell.api.Deployment")
	proto.RegisterType((*Resource)(nil), "darrell.api.Resource")
	proto.RegisterType((*DeploymentList)(nil), "darrell.api.DeploymentList")
	proto.RegisterType((*GetDeploymentRequest)(nil), "darrell.api.GetDeploymentRequest")
	proto.RegisterType((*ListDeploymentsRequest)(nil), "darrell.api.ListDeploymentsRequest")
}

func init() { proto.RegisterFile("deployment.proto", fileDescriptor4) }

var fileDescriptor4 = []byte{
	// 305 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x52, 0x4d, 0x4b, 0x33, 0x31,
	0x10, 0x26, 0xfd, 0xee, 0x14, 0xca, 0x4b, 0x78, 0xad, 0x41, 0x3c, 0x2c, 0x7b, 0x90, 0x5e, 0xdc,
	0x83, 0xbd, 0x79, 0x11, 0x44, 0xf0, 0xe2, 0x69, 0x8f, 0xde, 0xc6, 0xec, 0x28, 0x91, 0x6d, 0x37,
	0x26, 0xd3, 0x82, 0x3f, 0xd5, 0x7f, 0x23, 0x89, 0xd9, 0xee, 0x6a, 0x6f, 0xf3, 0x7c, 0xf0, 0x30,
	0x4f, 0x26, 0xf0, 0xaf, 0x22, 0x5b, 0x37, 0x9f, 0x5b, 0xda, 0x71, 0x61, 0x5d, 0xc3, 0x8d, 0x5c,
	0x54, 0xe8, 0x1c, 0xd5, 0x75, 0x81, 0xd6, 0xe4, 0x5f, 0x02, 0xe0, 0xe1, 0xe8, 0x90, 0x4b, 0x18,
	0x98, 0x4a, 0x89, 0x4c, 0xac, 0xe7, 0xe5, 0xc0, 0x54, 0x32, 0x83, 0x05, 0x5a, 0x5b, 0x1b, 0x8d,
	0x6c, 0x9a, 0x9d, 0x1a, 0x44, 0xa1, 0x4f, 0xc9, 0x15, 0x4c, 0x18, 0xdd, 0x1b, 0xb1, 0x1a, 0x46,
	0x31, 0x21, 0x79, 0x01, 0x33, 0x74, 0x6c, 0x5e, 0x51, 0xb3, 0x1a, 0x45, 0xe5, 0x88, 0xa5, 0x82,
	0xe9, 0x81, 0x9c, 0x0f, 0x89, 0xe3, 0x28, 0xb5, 0x30, 0xa4, 0xa1, 0x66, 0x73, 0x20, 0x35, 0xc9,
	0xc4, 0x7a, 0x56, 0x26, 0x24, 0x37, 0x30, 0x77, 0xe4, 0x9b, 0xbd, 0xd3, 0xe4, 0xd5, 0x34, 0x1b,
	0xae, 0x17, 0x37, 0x67, 0x45, 0xaf, 0x47, 0x51, 0x26, 0xb5, 0xec, 0x7c, 0xf9, 0x3b, 0xcc, 0x5a,
	0x5a, 0x4a, 0x18, 0xed, 0x70, 0x4b, 0xa9, 0x5a, 0x9c, 0xc3, 0x1a, 0xba, 0xde, 0x7b, 0x26, 0x97,
	0x8a, 0xb5, 0x50, 0x5e, 0xc2, 0x3c, 0x38, 0xbc, 0x45, 0x4d, 0xa9, 0x57, 0x47, 0x84, 0xac, 0x0a,
	0x19, 0x53, 0xad, 0x38, 0xe7, 0x77, 0xb0, 0xec, 0x9e, 0xf1, 0xc9, 0x78, 0x96, 0xd7, 0x30, 0x36,
	0x4c, 0x5b, 0xaf, 0x44, 0x5c, 0xf7, 0xfc, 0xd7, 0xba, 0x9d, 0xb7, 0xfc, 0x71, 0xe5, 0x57, 0xf0,
	0xff, 0x91, 0xb8, 0xc7, 0xd3, 0xc7, 0x9e, 0xfc, 0xc9, 0x45, 0xf2, 0x5b, 0x58, 0x85, 0xf8, 0xce,
	0xe8, 0x5b, 0xe7, 0x9f, 0x5b, 0x89, 0x93, 0x5b, 0xdd, 0x8f, 0x9f, 0x87, 0x68, 0xcd, 0xcb, 0x24,
	0xfe, 0x83, 0xcd, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x5c, 0x26, 0x39, 0x1a, 0x1b, 0x02, 0x00,
	0x00,
}
